## Assignment 2: Write a code, where porosity and permeability thresholds will be given by user and you will return final dataframe.

In [6]:
import numpy as np
import pandas as pd

In [7]:
depth = np.arange(1500,5400,200)
porosity = np.array([0.15,0.13,0.18,0.24,0.23,0.29,0.33,0.35,0.43,0.39,0.37,0.45,0.36,0.43,0.33,0.42,0.22,0.24,0.22,0.28])
permeability = [20,34,25,58,79,98,150,190,230,198,224,216,275,213,237,389,98,86,62,54]

field_data = {"Depth" : depth, "Porosity" : porosity, "Permeability" : permeability}
df = pd.DataFrame(field_data)

In [8]:
df

    Depth  Porosity  Permeability
0    1500      0.15            20
1    1700      0.13            34
2    1900      0.18            25
3    2100      0.24            58
4    2300      0.23            79
5    2500      0.29            98
6    2700      0.33           150
7    2900      0.35           190
8    3100      0.43           230
9    3300      0.39           198
10   3500      0.37           224
11   3700      0.45           216
12   3900      0.36           275
13   4100      0.43           213
14   4300      0.33           237
15   4500      0.42           389
16   4700      0.22            98
17   4900      0.24            86
18   5100      0.22            62
19   5300      0.28            54

In [9]:
poro_thresh = float(input("What is the porosity threshold? : "))
perm_thresh = float(input("What is the permeability threshold? : "))
print()

print(f"The zone(s) with porosity < {poro_thresh} and permeability < {perm_thresh} is/are as following:")

df[(df["Porosity"] < poro_thresh) & (df["Permeability"] < perm_thresh)]

What is the porosity threshold? : 0.33
What is the permeability threshold? : 250

The zone(s) with porosity < 0.33 and permeability < 250.0 is/are as following:

    Depth  Porosity  Permeability
0    1500      0.15            20
1    1700      0.13            34
2    1900      0.18            25
3    2100      0.24            58
4    2300      0.23            79
5    2500      0.29            98
16   4700      0.22            98
17   4900      0.24            86
18   5100      0.22            62
19   5300      0.28            54